apiVersion: v1
kind: Service
metadata:
  name: svcnginx
spec:
  selector:
    app: nginx
  ports:
   -  name: nginx
      port: 80
      protocol: TCP
   - name: mtool-http
     port: 8080
     protocol: TCP
     