apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
      - name: nginx
        image: nginx:latest
        ports:
         - containerPort: 80
           name: nginx-http         
      - name: multitool
        image: wbitt/network-multitool  
        env:
         - name: HTTP_PORT
           value: "8080"   
         - name: HTTPS_PORT
           value: "8443"  
        ports:
         - containerPort: 8080   
           name: multi-http
         - containerPort: 8443
           name: multi-https