apiVersion: v1
kind: Service
metadata:
  name: svcnginx
spec:
  selector:
    app: nginx
  ports:
   -  name: nginx-http
      port: 9001
      protocol: TCP
      targetPort: nginx-http
   - name: multi-http
     port: 9002
     protocol: TCP
     targetPort: multi-http