apiVersion: v1
kind: Service
metadata:
  name: svcnodeport
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: node-nginx
    protocol: TCP
    port: 9001
    targetPort: nginx-http
    nodePort: 30081
  - name: node-multi
    protocol: TCP
    port: 9002
    targetPort: multi-http
    nodePort: 30082