apiVersion: apps/v1
kind: Deployment
metadata:
  name: testvol
  labels:
    app: testvol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testvol
  template:
    metadata:
      labels:
        app: testvol
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo Hello >> /output/file.txt; sleep 5; done;']
        volumeMounts:
        - name: vol
          mountPath: /output
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: vol
          mountPath: /input
      volumes:
      - name: vol
        emptyDir: {}