---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector

handlers:
    - name: Reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
      
- name: Install Lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install Nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Create Nginx config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: Reload-nginx
  roles:
    - lighthouse